apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: us-east1-docker.pkg.dev/web-service-design/threads/nextjs
    newTag: __GITHUB_SHA__
  - name: us-east1-docker.pkg.dev/web-service-design/threads/ml-service
    newTag: __GITHUB_SHA__
