apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threads
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      nextjs=us-east1-docker.pkg.dev/web-service-design/threads/nextjs,
      ml-service=us-east1-docker.pkg.dev/web-service-design/threads/ml-service
    argocd-image-updater.argoproj.io/nextjs.update-strategy: latest
    argocd-image-updater.argoproj.io/nextjs.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/ml-service.update-strategy: latest
    argocd-image-updater.argoproj.io/ml-service.allow-tags: regexp:^[0-9a-f]{40}$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: ${repo_url}
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: threads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
